name: maskcheck
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  background_location: ^0.0.9+3
  camera: ^0.5.7+4
  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^1.4.3
  fluttertoast: ^7.1.1
  geolocator: ^5.3.1
  google_fonts: ^1.1.1
  path: ^1.6.4
  path_provider: ^1.6.7
  shared_preferences: ^0.5.7+1
  tflite: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/labels.txt
    - assets/converted_model.tflite
    - images/earth.jpg
    - images/bg.jpg
